### ISSUE TITLE
Provide "--no-lb" option

### ISSUE THREAD

**Issue by jeusdi** [keunlee/k3d-metallb-starter-kit#1]
Don't you think that `--no-lb` option should be provided on `k3d` cluster creation?

I mean, by default `k3d` deploys some kind of load balancer mechanism (I don't quite figure out).

Should it be removed?

**Comment by behroozam** [comment]
yeah default k3d svcloadbalancer use nodeport and the limiation it is you cant assign same port to service 
for example two loadbalancer service with 80 and 433 port cant be exist. 
but the MetalLB use range of ip in your pool and avoid this issue 
 I am using this config for create k3d cluster to disable default k3d svcloadbalancer 
 ```
cat <<EOF >> cluster1.yml
apiVersion: k3d.io/v1alpha3
kind: Simple
name: cluster-1
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6445"

options:
  k3d: # k3d runtime settings
    disableLoadbalancer: true # same as `--no-lb`
EOF

k3d cluster create --config cluster1.yml
```

**Comment by behroozam** [comment]
yeah default k3d svcloadbalancer use nodeport and the limiation it is you cant assign same port to service 
for example two loadbalancer service with 80 and 433 port cant be exist. 
but the MetalLB use range of ip in your pool and avoid this issue 
 I am using this config for create k3d cluster to disable default k3d svcloadbalancer 
 ```
cat <<EOF >> brightup.sh
apiVersion: k3d.io/v1alpha3
kind: Simple
name: cluster-1
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6445"

options:
  k3d: # k3d runtime settings
    disableLoadbalancer: true # same as `--no-lb`
EOF

```

**Comment by rakhbari** [comment]
I realize I'm a bit late to this thread, but just in case for others who happen upon it later, as of k3d version v5.4.6, the option for disabling the LB docker container is `disableLoadbalancer: true|false` under k3d's options.

I've also learned a few other k3s related options from [Techno Tim's docs](https://docs.technotim.live/posts/k3s-etcd-ansible/) which make k3s more responsive:

_Note:_ The last k3s option `node-status-update-frequency` has to be repeated for `nodeFilter: agent:*` for it to take effect. 
```
options:
  k3d: # k3d runtime settings
    disableLoadbalancer: true # same as `--no-lb`
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --kube-apiserver-arg=default-not-ready-toleration-seconds=30
        nodeFilters:
          - server:*
      - arg: --kube-apiserver-arg=default-unreachable-toleration-seconds=30
        nodeFilters:
          - server:*
      - arg: --kube-controller-arg=node-monitor-period=20s
        nodeFilters:
          - server:*
      - arg: --kube-controller-arg=node-monitor-grace-period=20s
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=node-status-update-frequency=5s
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=node-status-update-frequency=5s
        nodeFilters:
          - agent:*
```
