### ISSUE TITLE
configmap did not work for KinD cluster - but IP adresspool

### ISSUE THREAD

**Issue by lohithcode** [keunlee/k3d-metallb-starter-kit#6]
See --

- https://github.com/metallb/metallb/blob/main/configsamples/simple_pool_adv_l2.yaml
- https://metallb.universe.tf/configuration/
- create a yaml file and `kubectl apply -f <example.yaml>`

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/24
  - 192.168.9.1-192.168.9.5
  - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```
